Try to make openvpn auth handling work properly
Signed-off-by: Olaf Kirch <okir@suse.de>

diff --git a/extensions/functions b/extensions/functions
--- a/extensions/functions
+++ b/extensions/functions
@@ -115,6 +115,12 @@ function wicked_error {
 	exit 1
 }
 
+function wicked_auth_error {
+
+	echo "<error name=\"com.suse.Wicked.AuthInfoMissing\">$@</error>" >$WICKED_RETFILE
+	exit 1
+}
+
 function wicked_return_scalar {
 
 	echo "<return>$@</return>" >$WICKED_RETFILE
