openvpn: link-up now blocks until the openvpn tunnel is up
Build an addrconf lease file in the callback script.
The next step will be to inform wickedd about this lease, so that it
can track it properly.

Signed-off-by: Olaf Kirch <okir@suse.de>

diff --git a/extensions/openvpn b/extensions/openvpn
--- a/extensions/openvpn
+++ b/extensions/openvpn
@@ -1,21 +1,22 @@
 #!/bin/bash
 
+set -e
+umask 077
+
+scriptname=$0
 scriptdir=`dirname $0`
 if [ -f "$scriptdir/functions" ]; then
 	. "$scriptdir/functions"
 fi
 
-if [ -z "$WICKED_TUNNEL_ID" ]; then
-	echo "$0: no tunnel-id" >&2
-	exit 1
-fi
-
-set -e
-umask 077
-
-confdir=/var/run/wicked/$WICKED_TUNNEL_ID
-mkdir -m 700 -p $confdir
-
+##################################################################
+# Generate an openvpn config file from the XML data we've been
+# given.
+# It'd be tempting to do this with xsltproc, except that we need
+# to take care of incomplete auth information (and have the client
+# prompt for it), as well as copying the temporary key and cert files
+# to a permanent location.
+##################################################################
 function openvpn_update_config {
 
 	conffile="$confdir/config"
@@ -28,7 +29,6 @@ comp-lzo
 explicit-exit-notify 5
 EOF
 
-	set -x
 	echo "dev $WICKED_INTERFACE_NAME"
 
 	wicked_getargs 'authreq=%{config/auth/require}' 'user=%{config/auth/user}' 'pass=%{config/auth/password}'
@@ -77,7 +77,49 @@ EOF
 	fi
 
 	# Attention: add a script callback that notifies us when the link and addresses come up
+	echo "up \"$scriptname network-up-notify $WICKED_TUNNEL_ID\""
 }
+
+##################################################################
+# When the network has been brought up by openvpn, we're being
+# called back through the --up hook.
+# Build an addrconf lease.
+##################################################################
+function openvpn_build_lease {
+
+	filename=$1
+
+	wicked lease $filename add --address $ifconfig_local/32 --peer $ifconfig_remote
+
+	for n in ${!route_network_*}; do
+		index=${n//route_network_}
+		for var in network netmask gateway; do
+			eval $var=\$route_${var}_${index}
+		done
+
+		wicked lease $filename add --route $network --netmask $netmask --gateway $gateway
+	done
+}
+
+# Check if we're being called back from openvpn
+if [ "$1" = "network-up-notify" ]; then
+	WICKED_TUNNEL_ID=$2
+	shift 2
+
+	confdir=/var/run/wicked/$WICKED_TUNNEL_ID
+	mkdir -m 700 -p $confdir
+	openvpn_build_lease $confdir/lease
+
+	exit 0
+fi
+
+if [ -z "$WICKED_TUNNEL_ID" ]; then
+	echo "$0: no tunnel-id" >&2
+	exit 1
+fi
+
+confdir=/var/run/wicked/$WICKED_TUNNEL_ID
+mkdir -m 700 -p $confdir
 
 cmd=$1; shift
 case $cmd in
@@ -86,7 +128,23 @@ change)
 	: ;;
 
 link-up)
-	/usr/sbin/openvpn --daemon --writepid $confdir/pid --config $confdir/config --cd /etc/openvpn >/dev/null 2>&1 3>&1
+	rm -f $confdir/lease
+
+	/usr/sbin/openvpn --daemon $WICKED_TUNNEL_ID --writepid $confdir/pid --config $confdir/config --cd /etc/openvpn >/dev/null 2>&1 3>&1
+
+	# retries is in 10th of a second
+	retries=100
+	while [ ! -f $confdir/lease ]; do
+		if [ $retries -lt 0 ]; then
+			wicked_error "Timed out waiting for tunnel to come up"
+		fi
+
+		usleep 500000
+		let retries-=5
+	done
+
+	# Now inform wickedd about the lease
+	# wicked lease $confdir/lease send --addrconf intrinsic
 	: ;;
 
 link-down)
