Added missed action dummies to etc/init.d/network

diff --git a/etc/init.d/network.in b/etc/init.d/network.in
--- a/etc/init.d/network.in
+++ b/etc/init.d/network.in
@@ -128,4 +128,49 @@ stop)
 	rc_status -v
 	;;
 
+try-restart|condrestart)
+	$0 status
+	if test $? = 0; then
+		$0 restart
+	else
+		rc_reset        # Not running is not a failure.
+	fi
+	rc_status
+	;;
+
+restart)
+	$0 stop
+	$0 start
+	rc_status
+	;;
+
+force-reload)
+	echo -n "Reload service network"
+	$0 try-restart
+	rc_status
+	;;
+
+reload)
+	# Not yet
+	rc_failed 3
+	rc_status -v
+	;;
+
+status)
+	echo -n "Checking for service network "
+	# Dummy:
+	$WICKED_CLIENT_BIN show-xml &>/dev/null
+	rc_status -v
+	;;
+
+probe)
+	#test /etc/wicked/config.xml -nt /var/run/wicked.pid &&
+	echo restart
+	;;
+
+*)
+	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload}"
+	exit 1
+	;;
+
 esac
